# golangci-lint configuration for pulumicost-mcp
# Compatible with golangci-lint v2.x
# https://golangci-lint.run/usage/configuration/

version: 2

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - gen
    - vendor
    - testdata

output:
  formats:
    colored-line-number:
      path: stdout
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    # Core linters
    - govet
    - ineffassign
    - unused

    # Code quality
    - gocritic
    - gocyclo
    - misspell
    - unconvert
    - unparam

    # Bug detection
    - bodyclose
    - rowserrcheck
    - sqlclosecheck

    # Style
    - errorlint
    - predeclared
    - whitespace

  disable:
    - staticcheck   # TODO: Re-enable with proper ST1001 exclusion for design/ files
    - errcheck      # TODO: Re-enable with proper os.Unsetenv exclusion
    - gosec         # TODO: Re-enable with proper G304/G306 exclusions
    - revive        # TODO: Re-enable with proper dot-import exclusion for design/ files
    - exhaustive
    - exhaustruct
    - funlen
    - cyclop
    - nestif
    - testpackage
    - paralleltest
    - tparallel
    - forcetypeassert
    - nlreturn
    - wrapcheck

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (os.Unsetenv)  # OK to ignore in tests

  govet:
    settings:
      shadow:
        strict: false

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: increment-decrement
      - name: var-naming
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: indent-error-flow
      - name: errorf

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - unnamedResult
      - hugeParam

  gocyclo:
    min-complexity: 15

  staticcheck:
    checks:
      - "all"
      - "-ST1001"  # Allow dot imports (required for Goa DSL)

  gosec:
    excludes:
      - G104  # Duplicate of errcheck
      - G204  # Subprocess with variable - needed for plugins
      - G304  # File inclusion via variable - needed for config loading
      - G306  # File permissions - OK for test files

issues:
  exclude:
    # Ignore os.Unsetenv in defer statements (cleanup in tests)
    - "Error return value of `os.Unsetenv` is not checked"
    # Ignore file permissions in test files
    - "G306: Expect WriteFile permissions"
    # Allow file reading from variable in config
    - "G304: Potential file inclusion via variable"
    # Allow dot imports in design files (required for Goa DSL)
    - "ST1001: should not use dot imports"

  exclude-rules:
    # Exclude some linters from test files
    - path: _test\.go
      linters:
        - gocyclo
        - dupl

    # Exclude all linters for generated code
    - path: gen/
      linters:
        - all

    # Allow dot imports in design files (required for Goa DSL)
    - path: design/
      text: "ST1001"

  max-issues-per-linter: 0
  max-same-issues: 0
