openapi: 3.0.3
info:
  title: Analysis Service
  description: AI-powered cost optimization, anomaly detection, and budget tracking
  version: 1.0.0

servers:
  - url: http://localhost:8080/jsonrpc

paths:
  /analysis.get_recommendations:
    post:
      summary: Get cost optimization recommendations
      operationId: getRecommendations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - stack_name
              properties:
                stack_name:
                  type: string
                recommendation_types:
                  type: array
                  items:
                    type: string
                    enum: [RIGHTSIZING, RESERVED_INSTANCES, SPOT_INSTANCES, STORAGE_OPTIMIZATION]
                minimum_savings:
                  type: number
                  minimum: 0
      responses:
        '200':
          description: List of recommendations
          content:
            application/json:
              schema:
                type: object
                properties:
                  recommendations:
                    type: array
                    items:
                      $ref: '#/components/schemas/Recommendation'
      x-mcp-tool:
        name: get_optimization_recommendations
        description: Get AI-powered cost optimization recommendations

  /analysis.detect_anomalies:
    post:
      summary: Detect cost anomalies
      operationId: detectAnomalies
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - stack_name
                - time_range
              properties:
                stack_name:
                  type: string
                time_range:
                  $ref: '#/components/schemas/TimeRange'
                sensitivity:
                  type: string
                  enum: [LOW, MEDIUM, HIGH]
                  default: MEDIUM
      responses:
        '200':
          description: Detected anomalies
          content:
            application/json:
              schema:
                type: object
                properties:
                  anomalies:
                    type: array
                    items:
                      $ref: '#/components/schemas/Anomaly'
      x-mcp-tool:
        name: detect_cost_anomalies
        description: Identify unusual spending patterns

  /analysis.forecast:
    post:
      summary: Forecast future costs
      operationId: forecastCosts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - stack_name
                - forecast_period
              properties:
                stack_name:
                  type: string
                forecast_period:
                  $ref: '#/components/schemas/TimeRange'
                confidence_level:
                  type: number
                  minimum: 0.0
                  maximum: 1.0
                  default: 0.95
      responses:
        '200':
          description: Cost forecast
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Forecast'
      x-mcp-tool:
        name: forecast_costs
        description: Project future costs based on trends

  /analysis.track_budget:
    post:
      summary: Track budget status
      operationId: trackBudget
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - stack_name
                - budget_amount
                - period
              properties:
                stack_name:
                  type: string
                budget_amount:
                  type: number
                  minimum: 0
                period:
                  type: string
                  enum: [DAILY, WEEKLY, MONTHLY, YEARLY]
                alert_thresholds:
                  type: array
                  items:
                    type: number
                    minimum: 0
                    maximum: 100
      responses:
        '200':
          description: Budget status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BudgetStatus'
      x-mcp-tool:
        name: track_budget
        description: Monitor spending against budget with alerts

components:
  schemas:
    Recommendation:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
        resource_urn:
          type: string
        current_cost:
          type: number
        projected_savings:
          type: number
        confidence:
          type: string
          enum: [LOW, MEDIUM, HIGH]
        description:
          type: string
        action_steps:
          type: array
          items:
            type: string

    Anomaly:
      type: object
      properties:
        id:
          type: string
        timestamp:
          type: string
          format: date-time
        resource_urns:
          type: array
          items:
            type: string
        severity:
          type: string
          enum: [LOW, MEDIUM, HIGH, CRITICAL]
        current_cost:
          type: number
        baseline_cost:
          type: number
        deviation_percent:
          type: number
        potential_causes:
          type: array
          items:
            type: string

    Forecast:
      type: object
      properties:
        stack_name:
          type: string
        forecast_period:
          $ref: '#/components/schemas/TimeRange'
        data_points:
          type: array
          items:
            $ref: '#/components/schemas/ForecastPoint'
        confidence_level:
          type: number
        methodology:
          type: string

    ForecastPoint:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        predicted_cost:
          type: number
        lower_bound:
          type: number
        upper_bound:
          type: number

    BudgetStatus:
      type: object
      properties:
        budget_amount:
          type: number
        current_spending:
          type: number
        remaining:
          type: number
        burn_rate:
          type: number
        projected_end_date:
          type: string
          format: date-time
        status:
          type: string
          enum: [OK, WARNING, EXCEEDED]
        alerts:
          type: array
          items:
            type: object
            properties:
              threshold:
                type: number
              triggered:
                type: boolean

    TimeRange:
      type: object
      required:
        - start
        - end
      properties:
        start:
          type: string
          format: date-time
        end:
          type: string
          format: date-time
